master:
    grpc-server:
        port: 9000
        host: 192.168.1.9
    jre:
        filePath: d:/openjdk-13.0.2_linux-x64_bin.tar.gz
        folderName: jdk-13.0.2

spring:
    servlet:
        multipart:
            max-file-size: 64MB
            max-request-size: 64MB
